name = "appeallettergenerator-backend"
main = "src/server.ts"
compatibility_date = "2024-03-28"

[vars]

[[routes]]
pattern = "api.appeallettergenerator.com"
custom_domain = true

[observability]
enabled = true