import { Insurer } from '@/types';

export const insurers: Insurer[] = [
    { slug: 'unitedhealthcare', name: 'UnitedHealthcare', shortName: 'UHC', appealEmail: 'appeals@uhc.com', appealAddress: 'UnitedHealthcare Appeals, P.O. Box 30432, Salt Lake City, UT 84130', appealPhone: '1-800-842-2656', appealFax: '1-801-938-1026', filingDeadlineDays: 180, website: 'https://www.uhc.com', tips: ['Always request a peer-to-peer review with your doctor', 'Reference UHC Clinical Policy Bulletins in your appeal', 'Include treating physician letter of medical necessity', 'File with state DOI if internal appeal denied'], commonDenialReasons: ['not-medically-necessary', 'pre-authorization', 'out-of-network', 'experimental'], successRate: 54, statesOperating: ['ALL'], parentCompany: 'UnitedHealth Group' },
    { slug: 'anthem', name: 'Anthem Blue Cross Blue Shield', shortName: 'Anthem', appealEmail: 'appeals@anthem.com', appealAddress: 'Anthem Appeals, P.O. Box 105187, Atlanta, GA 30348', appealPhone: '1-800-331-1476', appealFax: '1-866-297-9295', filingDeadlineDays: 180, website: 'https://www.anthem.com', tips: ['Request Clinical Policy Bulletin used for denial', 'Cite AMA guidelines supporting your treatment', 'File expedited appeal for urgent situations', 'Contact state insurance commissioner if denied twice'], commonDenialReasons: ['not-medically-necessary', 'coding-error', 'pre-authorization', 'experimental'], successRate: 51, statesOperating: ['CA', 'CO', 'CT', 'GA', 'IN', 'KY', 'ME', 'MO', 'NH', 'NV', 'NY', 'OH', 'VA', 'WI'], parentCompany: 'Elevance Health' },
    { slug: 'aetna', name: 'Aetna', shortName: 'Aetna', appealEmail: 'appeals@aetna.com', appealAddress: 'Aetna Appeals, P.O. Box 14079, Lexington, KY 40512', appealPhone: '1-888-632-3862', appealFax: '1-860-754-5440', filingDeadlineDays: 180, website: 'https://www.aetna.com', tips: ['Reference Aetna Clinical Policy Bulletins (CPBs)', 'Include peer-reviewed medical literature', 'Request an expedited appeal for urgent needs', 'Cite ERISA full and fair review requirements'], commonDenialReasons: ['not-medically-necessary', 'pre-authorization', 'not-covered', 'experimental'], successRate: 49, statesOperating: ['ALL'], parentCompany: 'CVS Health' },
    { slug: 'cigna', name: 'Cigna Healthcare', shortName: 'Cigna', appealEmail: 'appeals@cigna.com', appealAddress: 'Cigna Appeals, P.O. Box 188011, Chattanooga, TN 37422', appealPhone: '1-800-244-6224', appealFax: '1-859-410-3130', filingDeadlineDays: 180, website: 'https://www.cigna.com', tips: ['Note the strict 14-day deadline for some plan types', 'Reference Cigna Medical Coverage Policies', 'Include clinical notes and test results', 'Request concurrent/expedited review when appropriate'], commonDenialReasons: ['not-medically-necessary', 'pre-authorization', 'timely-filing', 'out-of-network'], successRate: 47, statesOperating: ['ALL'], parentCompany: 'The Cigna Group' },
    { slug: 'bcbs', name: 'Blue Cross Blue Shield', shortName: 'BCBS', appealEmail: 'appeals@bcbs.com', appealAddress: 'Varies by state plan - check your member ID card', appealPhone: '1-800-262-2583', appealFax: 'Varies by state plan', filingDeadlineDays: 180, website: 'https://www.bcbs.com', tips: ['Each state plan has different appeal procedures', 'Check your specific BCBS plan documents', 'Reference BCBS Medical Policy guidelines', 'File with your state BCBS plan, not national'], commonDenialReasons: ['not-medically-necessary', 'coding-error', 'duplicate-claim', 'pre-authorization'], successRate: 52, statesOperating: ['ALL'], parentCompany: 'Blue Cross Blue Shield Association' },
    { slug: 'humana', name: 'Humana', shortName: 'Humana', appealEmail: 'appeals@humana.com', appealAddress: 'Humana Appeals, P.O. Box 14618, Lexington, KY 40512', appealPhone: '1-800-457-4708', appealFax: '1-877-260-7253', filingDeadlineDays: 180, website: 'https://www.humana.com', tips: ['Humana has specific Medicare Advantage appeal rules', 'Request Organization Determination for Medicare plans', 'Include treating physician support letter', 'File with state DOI and CMS for Medicare issues'], commonDenialReasons: ['not-medically-necessary', 'out-of-network', 'pre-authorization', 'not-covered'], successRate: 50, statesOperating: ['ALL'], parentCompany: 'Humana Inc.' },
    { slug: 'kaiser', name: 'Kaiser Permanente', shortName: 'Kaiser', appealEmail: 'appeals@kaiserpermanente.org', appealAddress: 'Kaiser Permanente Appeals, varies by region', appealPhone: '1-800-464-4000', appealFax: 'Varies by region', filingDeadlineDays: 180, website: 'https://www.kaiserpermanente.org', tips: ['Use DMHC Independent Medical Review in California', 'Kaiser is both insurer and provider - leverage this', 'Request patient advocate assistance', 'File with DMHC for California members'], commonDenialReasons: ['not-medically-necessary', 'experimental', 'not-covered', 'pre-authorization'], successRate: 56, statesOperating: ['CA', 'CO', 'DC', 'GA', 'HI', 'MD', 'OR', 'VA', 'WA'], parentCompany: 'Kaiser Foundation Health Plan' },
    { slug: 'molina', name: 'Molina Healthcare', shortName: 'Molina', appealEmail: 'appeals@molinahealthcare.com', appealAddress: 'Molina Healthcare Appeals, 200 Oceangate, Suite 100, Long Beach, CA 90802', appealPhone: '1-888-562-5442', appealFax: '1-562-499-0610', filingDeadlineDays: 180, website: 'https://www.molinahealthcare.com', tips: ['Molina primarily covers Medicaid/Marketplace plans', 'State Medicaid fair hearing rights may apply', 'Include all clinical documentation', 'Contact state Medicaid agency for additional help'], commonDenialReasons: ['not-medically-necessary', 'pre-authorization', 'out-of-network', 'not-covered'], successRate: 48, statesOperating: ['CA', 'FL', 'IL', 'MI', 'NM', 'NY', 'OH', 'SC', 'TX', 'UT', 'WA', 'WI'], parentCompany: 'Molina Healthcare Inc.' },
    { slug: 'centene', name: 'Centene / Ambetter', shortName: 'Centene', appealEmail: 'appeals@centene.com', appealAddress: 'Centene Appeals, 7700 Forsyth Blvd, St. Louis, MO 63105', appealPhone: '1-866-830-0560', appealFax: '1-866-830-0570', filingDeadlineDays: 180, website: 'https://www.centene.com', tips: ['Ambetter plans have specific marketplace appeal rights', 'ACA marketplace appeal protections apply', 'Request all clinical criteria used in denial', 'File with state DOI and CMS marketplace complaints'], commonDenialReasons: ['not-medically-necessary', 'pre-authorization', 'out-of-network', 'timely-filing'], successRate: 46, statesOperating: ['ALL'], parentCompany: 'Centene Corporation' },
    { slug: 'oscar', name: 'Oscar Health', shortName: 'Oscar', appealEmail: 'appeals@hioscar.com', appealAddress: 'Oscar Health Appeals, 75 Varick Street, New York, NY 10013', appealPhone: '1-855-672-2788', appealFax: '1-646-330-7985', filingDeadlineDays: 180, website: 'https://www.hioscar.com', tips: ['Oscar is a newer insurer - appeal processes may be faster', 'Use concierge team to assist with appeals', 'ACA marketplace protections fully apply', 'Request peer-to-peer review'], commonDenialReasons: ['not-medically-necessary', 'out-of-network', 'pre-authorization', 'not-covered'], successRate: 53, statesOperating: ['AZ', 'CA', 'CO', 'CT', 'FL', 'GA', 'KS', 'MI', 'MO', 'NJ', 'NY', 'OH', 'OK', 'PA', 'TN', 'TX', 'VA'], parentCompany: 'Oscar Health Inc.' },
];

export function getInsurer(slug: string): Insurer | undefined {
    return insurers.find(i => i.slug === slug);
}

export function getAllInsurerSlugs(): string[] {
    return insurers.map(i => i.slug);
}

export function searchInsurers(query: string): Insurer[] {
    const q = query.toLowerCase();
    return insurers.filter(i => i.name.toLowerCase().includes(q) || i.shortName.toLowerCase().includes(q) || i.slug.includes(q));
}
