import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | AppealLetterGenerator.com",
  description:
    "Terms of service and legal disclaimers for using AppealLetterGenerator.com's insurance appeal letter generator.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold mb-8 text-white">Terms of Service</h1>
      <div className="prose prose-invert max-w-none space-y-8 text-slate-300">
        <p className="text-slate-400 italic">Last updated: March 28, 2026</p>

        <section>
          <h2 className="text-xl font-bold text-white">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using AppealLetterGenerator.com (&ldquo;the
            Website&rdquo;), you agree to be bound by these Terms of Service. If
            you do not agree to these terms, please do not use the Website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white">2. Not Legal Advice</h2>
          <div className="bg-amber-500/10 border border-amber-500/20 p-4 rounded-lg text-amber-200 text-sm">
            <strong>IMPORTANT:</strong> AppealLetterGenerator.com is an
            automated technology platform. It is not a law firm and does not
            provide legal advice or legal representation. The appeal letters
            generated are templates based on user input and general insurance
            laws.
          </div>
          <ul className="list-disc pl-5 mt-4 space-y-2">
            <li>
              We do not guarantee the success of any appeal generated by our
              tool.
            </li>
            <li>
              We recommend that you have all legal documents reviewed by a
              licensed attorney.
            </li>
            <li>
              No attorney-client relationship is formed by your use of this
              Website.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white">
            3. User Responsibilities
          </h2>
          <p>
            You are solely responsible for the accuracy of the information you
            provide. You agree not to use the Website for any fraudulent
            purposes, including submitting false medical information or
            impersonating others.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white">
            4. Intellectual Property
          </h2>
          <p>
            The content, logos, and software used on AppealLetterGenerator.com
            are the property of the Website owners and are protected by
            copyright and intellectual property laws. You may use the generated
            appeal letters for your personal, non-commercial use only.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white">
            5. Limitation of Liability
          </h2>
          <p>
            In no event shall AppealLetterGenerator.com or its owners be liable
            for any damages (including, without limitation, damages for loss of
            health coverage, financial loss, or personal injury) arising out of
            the use or inability to use the materials on the Website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white">6. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Your
            continued use of the Website after changes are posted constitutes
            acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white">7. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
            appeallettergenerator@gmail.com
          </p>
        </section>
      </div>
    </div>
  );
}
