import { Hono } from "hono";
import { getInsurer } from "../lib/insurerDB";

const router = new Hono();

router.post("/", async (c) => {
  try {
    const {
      insurer,
      amount,
      claimNumber,
      dateOfService,
      patientName,
      procedureDescription,
      policyNumber,
    } = await c.req.json();

    if (!amount || !patientName) {
      return c.json({ error: "Missing required fields." }, 400);
    }

    const insurerData = getInsurer(insurer);

    const letter = `[YOUR NAME]
[YOUR ADDRESS]
[CITY, STATE ZIP]
[DATE]

Dispute Resolution Department
[YOUR BANK / CREDIT CARD COMPANY]
[BANK ADDRESS]

RE: CHARGEBACK / DISPUTE REQUEST
Transaction Amount: $${Number(amount).toLocaleString()}
Transaction Date: ${dateOfService || "[Date of Service]"}
Merchant: ${insurerData?.name || "[Insurance Company]"}
Reference: ${claimNumber || "[Claim Number]"}

Dear Dispute Resolution Team,

I am formally requesting a chargeback/dispute for the above transaction under the applicable card network reason codes:

- Visa: Reason Code 13.1 (Merchandise/Services Not Received or Not as Described)
- Mastercard: Reason Code 4853 (Goods/Services Not as Described)
- Amex: Reason Code C31 (Goods/Services Not as Described)

BACKGROUND:
I paid $${Number(amount).toLocaleString()} out-of-pocket for ${procedureDescription || "medical services"} on ${dateOfService || "[date]"} because my health insurance claim was denied by ${insurerData?.name || "[insurer]"}.

THE DISPUTE:
1. My health insurance policy #${policyNumber || "[number]"} with ${insurerData?.name || "[insurer]"} should have covered this service.
2. The insurance claim #${claimNumber || "[number]"} was improperly denied.
3. I have formally appealed this denial with the insurance company.
4. I should not bear the financial burden of an improperly denied insurance claim.

REQUEST:
Please initiate a chargeback for $${Number(amount).toLocaleString()} and issue a provisional credit to my account while this dispute is investigated.

ENCLOSED DOCUMENTATION:
1. Copy of insurance denial letter
2. Copy of formal appeal letter submitted to insurer
3. Medical records supporting necessity of services
4. Copy of insurance policy showing covered benefits

I am available at [YOUR PHONE] or [YOUR EMAIL] for any questions.

Sincerely,

${patientName || "[YOUR NAME]"}

---
Generated by AppealLetterGenerator.com - This is a template. Not legal advice.`;

    return c.json({ letter, success: true });
  } catch (error) {
    console.error("Chargeback API Error:", error);
    return c.json({ error: "Failed to generate chargeback letter." }, 500);
  }
});

export default router;
