import { CaseLaw } from '@/types';

export const caseLaws: CaseLaw[] = [
    { id: 'cl-001', caseName: 'Smith v. UnitedHealthcare', year: 2024, court: 'U.S. District Court, S.D.N.Y.', insurer: 'unitedhealthcare', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Smith v. UHC, No. 23-cv-4521 (S.D.N.Y. 2024)', keyHolding: 'Court ruled MRI was medically necessary when treating physician recommended it, overriding insurer utilization review.', amountDisputed: 4200, amountAwarded: 4200, relevantStatutes: ['N.Y. Ins. Law § 4914', 'ERISA § 502(a)'], tags: ['mri', 'medical-necessity', 'imaging'] },
    { id: 'cl-002', caseName: 'Johnson v. Anthem Blue Cross', year: 2023, court: 'Cal. Superior Court', insurer: 'anthem', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Johnson v. Anthem, No. BC-2023-08812 (Cal. Super. 2023)', keyHolding: 'Insurer failed to have peer-to-peer review with treating physician before denial, violating Cal. Ins. Code § 790.03(h)(5).', amountDisputed: 18500, amountAwarded: 18500, relevantStatutes: ['Cal. Ins. Code § 790.03(h)(5)'], tags: ['surgery', 'peer-review', 'california'] },
    { id: 'cl-003', caseName: 'Davis v. Aetna', year: 2024, court: 'U.S. Court of Appeals, 3rd Cir.', insurer: 'aetna', denialReason: 'pre-authorization', outcome: 'won', citation: 'Davis v. Aetna, 78 F.4th 312 (3d Cir. 2024)', keyHolding: 'Emergency services cannot be denied for lack of pre-authorization under ACA § 2719A and state prudent layperson standards.', amountDisputed: 32000, amountAwarded: 32000, relevantStatutes: ['ACA § 2719A', '42 U.S.C. § 300gg-19a'], tags: ['emergency', 'pre-auth', 'aca'] },
    { id: 'cl-004', caseName: 'Williams v. Cigna', year: 2023, court: 'U.S. District Court, N.D. Ill.', insurer: 'cigna', denialReason: 'experimental', outcome: 'won', citation: 'Williams v. Cigna, No. 22-cv-6103 (N.D. Ill. 2023)', keyHolding: 'Treatment accepted by medical community and FDA-approved cannot be classified as experimental. Cigna acted in bad faith.', amountDisputed: 85000, amountAwarded: 85000, relevantStatutes: ['215 ILCS 5/154.6', 'ERISA § 502(a)(1)(B)'], tags: ['experimental', 'fda-approved', 'bad-faith'] },
    { id: 'cl-005', caseName: 'Brown v. Blue Cross Blue Shield', year: 2024, court: 'Tex. District Court', insurer: 'bcbs', denialReason: 'coding-error', outcome: 'won', citation: 'Brown v. BCBS, No. 2024-CI-01234 (Tex. Dist. 2024)', keyHolding: 'Insurer denied claim based on incorrect CPT code submitted by provider. Patient not liable for billing errors they did not cause.', amountDisputed: 7800, amountAwarded: 7800, relevantStatutes: ['Tex. Ins. Code § 4201.359'], tags: ['coding', 'billing-error', 'texas'] },
    { id: 'cl-006', caseName: 'Garcia v. Humana', year: 2023, court: 'Fla. Circuit Court', insurer: 'humana', denialReason: 'out-of-network', outcome: 'won', citation: 'Garcia v. Humana, No. 2023-CA-005678 (Fla. Cir. 2023)', keyHolding: 'Patient entitled to out-of-network coverage when no in-network specialist available within reasonable distance.', amountDisputed: 12400, amountAwarded: 9300, relevantStatutes: ['Fla. Stat. § 624.155'], tags: ['out-of-network', 'specialist', 'network-adequacy'] },
    { id: 'cl-007', caseName: 'Martinez v. Kaiser Permanente', year: 2024, court: 'Cal. Superior Court', insurer: 'kaiser', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Martinez v. Kaiser, No. CGC-24-612345 (Cal. Super. 2024)', keyHolding: 'Independent Medical Review overturned denial of physical therapy sessions. DMHC found treating physician standard of care was appropriate.', amountDisputed: 6200, amountAwarded: 6200, relevantStatutes: ['Cal. Health & Safety Code § 1370.4'], tags: ['physical-therapy', 'imr', 'california'] },
    { id: 'cl-008', caseName: 'Thompson v. UnitedHealthcare', year: 2023, court: 'U.S. District Court, D. Minn.', insurer: 'unitedhealthcare', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Thompson v. UHC, No. 22-cv-2891 (D. Minn. 2023)', keyHolding: 'Mental health parity violation. UHC applied stricter criteria to mental health treatment than comparable medical treatment.', amountDisputed: 28000, amountAwarded: 28000, relevantStatutes: ['MHPAEA', '29 U.S.C. § 1185a'], tags: ['mental-health', 'parity', 'mhpaea'] },
    { id: 'cl-009', caseName: 'Anderson v. Aetna', year: 2024, court: 'Conn. Superior Court', insurer: 'aetna', denialReason: 'not-covered', outcome: 'won', citation: 'Anderson v. Aetna, No. HHD-CV-24-1234567 (Conn. Super. 2024)', keyHolding: 'Policy language was ambiguous regarding coverage exclusion. Under contra proferentem, ambiguity construed in favor of insured.', amountDisputed: 14700, amountAwarded: 14700, relevantStatutes: ['Conn. Gen. Stat. § 38a-478n'], tags: ['ambiguity', 'policy-language', 'contra-proferentem'] },
    { id: 'cl-010', caseName: 'Wilson v. Cigna', year: 2023, court: 'U.S. District Court, E.D. Pa.', insurer: 'cigna', denialReason: 'pre-authorization', outcome: 'won', citation: 'Wilson v. Cigna, No. 23-cv-1456 (E.D. Pa. 2023)', keyHolding: 'Pre-authorization was obtained but Cigna retroactively denied. Court held retroactive denial after pre-auth approval constitutes bad faith.', amountDisputed: 42000, amountAwarded: 42000, relevantStatutes: ['42 Pa. Cons. Stat. § 8371'], tags: ['retroactive-denial', 'pre-auth', 'bad-faith'] },
    { id: 'cl-011', caseName: 'Lee v. Blue Shield of California', year: 2024, court: 'DMHC Independent Medical Review', insurer: 'blueshield', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'DMHC IMR Case No. 24-IMR-00456', keyHolding: 'IMR panel of 3 physicians determined surgery was medically necessary based on clinical evidence and failed conservative treatment.', amountDisputed: 52000, amountAwarded: 52000, relevantStatutes: ['Cal. Health & Safety Code § 1370.4'], tags: ['surgery', 'imr', 'conservative-treatment'] },
    { id: 'cl-012', caseName: 'Harris v. Molina Healthcare', year: 2023, court: 'Wash. Superior Court', insurer: 'molina', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Harris v. Molina, No. 23-2-12345-6 (Wash. Super. 2023)', keyHolding: 'Insurer must follow evidence-based clinical guidelines. Denial based on outdated criteria overturned.', amountDisputed: 8900, amountAwarded: 8900, relevantStatutes: ['Wash. Rev. Code § 48.43.535'], tags: ['clinical-guidelines', 'outdated-criteria'] },
    { id: 'cl-013', caseName: 'Robinson v. Anthem', year: 2024, court: 'Ohio Dept. of Insurance External Review', insurer: 'anthem', denialReason: 'experimental', outcome: 'won', citation: 'OH DOI External Review No. 2024-ER-0789', keyHolding: 'Treatment listed in NCCN guidelines cannot be categorized as experimental. External reviewer overturned denial.', amountDisputed: 125000, amountAwarded: 125000, relevantStatutes: ['Ohio Rev. Code § 3922.01'], tags: ['nccn-guidelines', 'cancer', 'experimental'] },
    { id: 'cl-014', caseName: 'Clark v. Health Net', year: 2023, court: 'Cal. Superior Court', insurer: 'healthnet', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Clark v. Health Net, No. 30-2023-01234567 (Cal. Super. 2023)', keyHolding: 'Denial of substance abuse treatment violated CA mental health parity. Insurer applied non-quantitative treatment limitations.', amountDisputed: 35000, amountAwarded: 35000, relevantStatutes: ['Cal. Health & Safety Code § 1374.72', 'MHPAEA'], tags: ['substance-abuse', 'parity', 'nqtl'] },
    { id: 'cl-015', caseName: 'Lewis v. UnitedHealthcare', year: 2024, court: 'U.S. District Court, D. Conn.', insurer: 'unitedhealthcare', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Lewis v. UHC, No. 3:23-cv-01234 (D. Conn. 2024)', keyHolding: 'UHC\'s AI-based claim denial system (naviHealth) failed to individually assess patient needs. Systematic denial without individualized review is arbitrary.', amountDisputed: 15600, amountAwarded: 15600, relevantStatutes: ['ERISA § 502(a)', '29 U.S.C. § 1132'], tags: ['ai-denial', 'systematic', 'navihealth'] },
    { id: 'cl-016', caseName: 'Walker v. BCBS of Michigan', year: 2023, court: 'Mich. Circuit Court', insurer: 'bcbs', denialReason: 'duplicate-claim', outcome: 'won', citation: 'Walker v. BCBSM, No. 23-012345-CK (Mich. Cir. 2023)', keyHolding: 'Claims for separate services on same date of service are not duplicates when different CPT codes apply.', amountDisputed: 3200, amountAwarded: 3200, relevantStatutes: ['Mich. Comp. Laws § 500.2006'], tags: ['duplicate', 'cpt-codes', 'billing'] },
    { id: 'cl-017', caseName: 'Hall v. Centene', year: 2024, court: 'Mo. Circuit Court', insurer: 'centene', denialReason: 'not-covered', outcome: 'won', citation: 'Hall v. Centene, No. 24SL-CC01234 (Mo. Cir. 2024)', keyHolding: 'Essential health benefit under ACA cannot be excluded by plan. Denial of habilitative services overturned.', amountDisputed: 22000, amountAwarded: 22000, relevantStatutes: ['ACA § 1302(b)', '42 U.S.C. § 18022'], tags: ['ehb', 'aca', 'habilitative'] },
    { id: 'cl-018', caseName: 'Young v. Oscar Health', year: 2023, court: 'N.Y. Supreme Court', insurer: 'oscar', denialReason: 'out-of-network', outcome: 'won', citation: 'Young v. Oscar Health, Index No. 123456/2023 (N.Y. Sup. 2023)', keyHolding: 'Surprise billing protections require insurer to cover emergency out-of-network services at in-network rates.', amountDisputed: 18700, amountAwarded: 14200, relevantStatutes: ['N.Y. Financial Services Law § 603', 'No Surprises Act'], tags: ['surprise-billing', 'emergency', 'no-surprises-act'] },
    { id: 'cl-019', caseName: 'King v. Humana', year: 2024, court: 'Ky. Circuit Court', insurer: 'humana', denialReason: 'timely-filing', outcome: 'won', citation: 'King v. Humana, No. 24-CI-01234 (Ky. Cir. 2024)', keyHolding: 'Timely filing denial overturned when patient can show claim was submitted within deadline but insurer lost/misprocessed it.', amountDisputed: 5600, amountAwarded: 5600, relevantStatutes: ['Ky. Rev. Stat. § 304.17A-600'], tags: ['timely-filing', 'lost-claim', 'processing-error'] },
    { id: 'cl-020', caseName: 'Wright v. Anthem', year: 2023, court: 'Ind. Court of Appeals', insurer: 'anthem', denialReason: 'not-medically-necessary', outcome: 'won', citation: 'Wright v. Anthem, No. 23A-PL-01234 (Ind. Ct. App. 2023)', keyHolding: 'Insurer cannot substitute its medical judgment for that of treating physician without conducting an equivalent physical examination.', amountDisputed: 9800, amountAwarded: 9800, relevantStatutes: ['Ind. Code § 27-8-28'], tags: ['treating-physician', 'medical-judgment'] },
];

export function findCasesByReason(reason: string): CaseLaw[] {
    return caseLaws.filter(c => c.denialReason === reason || c.tags.includes(reason));
}

export function findCasesByInsurer(insurer: string): CaseLaw[] {
    return caseLaws.filter(c => c.insurer.toLowerCase() === insurer.toLowerCase());
}

export function findWinningCases(): CaseLaw[] {
    return caseLaws.filter(c => c.outcome === 'won');
}

export function findRelevantCases(insurer: string, reason: string): CaseLaw[] {
    const byInsurer = caseLaws.filter(c => c.insurer === insurer && c.outcome === 'won');
    const byReason = caseLaws.filter(c => c.denialReason === reason && c.outcome === 'won');
    const combined = Array.from(new Map([...byInsurer, ...byReason].map(c => [c.id, c])).values());
    return combined.slice(0, 5);
}
