// ============================================================
// AppealLetterGenerator.com - State Insurance Law Database
// 50 US States + DC + UK + Canada + Australia
// ============================================================

import { StateLaw } from "@/types";

export const stateLaws: StateLaw[] = [
  // ── US STATES ──────────────────────────────────────────────
  {
    code: "AL",
    name: "Alabama",
    country: "US",
    statute: "Alabama Insurance Code",
    statuteCitation: "Ala. Code § 27-1-1 et seq.",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Alabama Department of Insurance",
    departmentPhone: "(334) 269-3550",
    departmentUrl: "https://www.aldoi.gov",
    keyProvisions: [
      "Insurers must provide written denial with specific reasons",
      "Policyholders have right to internal appeal",
      "External review available for adverse benefit determinations",
      "Bad faith denial penalties under Ala. Code § 27-12-11",
    ],
    penaltyForNonCompliance:
      "Fines up to $1,000 per violation plus potential license revocation",
  },
  {
    code: "AK",
    name: "Alaska",
    country: "US",
    statute: "Alaska Insurance Code",
    statuteCitation: "Alaska Stat. § 21.36.125",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Alaska Division of Insurance",
    departmentPhone: "(907) 269-7900",
    departmentUrl: "https://www.commerce.alaska.gov/web/ins/",
    keyProvisions: [
      "Written denial must include specific reasons and right to appeal",
      "Internal appeal must be completed within 30 days",
      "External review for medical necessity denials",
      "Unfair claims practices act: Alaska Stat. § 21.36.125",
    ],
    penaltyForNonCompliance: "Fines up to $2,500 per violation",
  },
  {
    code: "AZ",
    name: "Arizona",
    country: "US",
    statute: "Arizona Insurance Code",
    statuteCitation: "Ariz. Rev. Stat. § 20-461",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance:
      "Arizona Department of Insurance and Financial Institutions",
    departmentPhone: "(602) 364-3100",
    departmentUrl: "https://difi.az.gov",
    keyProvisions: [
      "Insurers must respond to claims within 30 days",
      "Written denial required with appeal instructions",
      "Independent external review for medical necessity",
      "Bad faith penalties: Ariz. Rev. Stat. § 20-461",
    ],
    penaltyForNonCompliance:
      "Fines up to $5,000 per violation plus treble damages",
  },
  {
    code: "AR",
    name: "Arkansas",
    country: "US",
    statute: "Arkansas Insurance Code",
    statuteCitation: "Ark. Code Ann. § 23-66-206",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Arkansas Insurance Department",
    departmentPhone: "(501) 371-2600",
    departmentUrl: "https://insurance.arkansas.gov",
    keyProvisions: [
      "Unfair claims settlement practices prohibited",
      "Written denial with specific reasons required",
      "Right to internal and external appeal",
      "Prompt payment requirements",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "CA",
    name: "California",
    country: "US",
    statute: "California Insurance Code - Fair Claims Settlement Practices",
    statuteCitation: "Cal. Ins. Code § 790.03(h)(5)",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "California Department of Insurance",
    departmentPhone: "(800) 927-4357",
    departmentUrl: "https://www.insurance.ca.gov",
    keyProvisions: [
      "Insurers must acknowledge claims within 15 days",
      "Decisions must be made within 40 days",
      "Written denial with specific factual and legal basis required",
      "Independent Medical Review (IMR) for HMO/PPO denials",
      "Bad faith penalties: Cal. Ins. Code § 790.03(h)",
      "DMHC external review for health plan denials",
    ],
    penaltyForNonCompliance:
      "Fines up to $10,000 per violation, license suspension, bad faith damages",
  },
  {
    code: "CO",
    name: "Colorado",
    country: "US",
    statute: "Colorado Insurance Code",
    statuteCitation: "Colo. Rev. Stat. § 10-16-113",
    filingDeadlineDays: 60,
    externalReviewAvailable: true,
    departmentOfInsurance: "Colorado Division of Insurance",
    departmentPhone: "(303) 894-7499",
    departmentUrl: "https://doi.colorado.gov",
    keyProvisions: [
      "Mandatory external review for medical necessity denials",
      "Insurers must notify of appeal rights within denial letter",
      "Expedited review for urgent situations (72 hours)",
      "Protections under Colorado Consumer Protection Act",
    ],
    penaltyForNonCompliance:
      "Administrative penalties plus potential license action",
  },
  {
    code: "CT",
    name: "Connecticut",
    country: "US",
    statute: "Connecticut Insurance Code",
    statuteCitation: "Conn. Gen. Stat. § 38a-478n",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Connecticut Insurance Department",
    departmentPhone: "(860) 297-3800",
    departmentUrl: "https://portal.ct.gov/cid",
    keyProvisions: [
      "Mandatory internal and external grievance procedures",
      "Independent external review binding on insurer",
      "Written denial must include clinical rationale",
      "Consumer protections under Conn. Gen. Stat. § 38a-815",
    ],
    penaltyForNonCompliance: "Fines up to $5,000 per violation",
  },
  {
    code: "DE",
    name: "Delaware",
    country: "US",
    statute: "Delaware Insurance Code",
    statuteCitation: "Del. Code Ann. tit. 18, § 2304",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Delaware Department of Insurance",
    departmentPhone: "(302) 674-7300",
    departmentUrl: "https://insurance.delaware.gov",
    keyProvisions: [
      "Unfair claims settlement practices act",
      "Written denial with appeal rights required",
      "External review process for adverse determinations",
      "Prompt pay requirements",
    ],
    penaltyForNonCompliance: "Fines up to $5,000 per violation",
  },
  {
    code: "FL",
    name: "Florida",
    country: "US",
    statute: "Florida Insurance Code",
    statuteCitation: "Fla. Stat. § 624.155",
    filingDeadlineDays: 60,
    externalReviewAvailable: true,
    departmentOfInsurance: "Florida Office of Insurance Regulation",
    departmentPhone: "(850) 413-3140",
    departmentUrl: "https://www.floir.com",
    keyProvisions: [
      "Bad faith cause of action: Fla. Stat. § 624.155",
      "Written denial required within 30 days",
      "External review rights for HMO enrollees",
      "Civil remedy notice required before bad faith suit",
      "Extra-contractual damages available in bad faith",
    ],
    penaltyForNonCompliance:
      "Bad faith damages including attorney fees and costs",
  },
  {
    code: "GA",
    name: "Georgia",
    country: "US",
    statute: "Georgia Insurance Code",
    statuteCitation: "Ga. Code Ann. § 33-4-6",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance:
      "Georgia Office of Insurance and Safety Fire Commissioner",
    departmentPhone: "(404) 656-2070",
    departmentUrl: "https://oci.georgia.gov",
    keyProvisions: [
      "Bad faith penalties: 50% penalty plus attorney fees",
      "Written denial with reasons required",
      "External review for medical necessity denials",
      "Ga. Code Ann. § 33-4-6 bad faith provisions",
    ],
    penaltyForNonCompliance:
      "Up to 50% penalty on claim amount plus attorney fees",
  },
  {
    code: "HI",
    name: "Hawaii",
    country: "US",
    statute: "Hawaii Insurance Code",
    statuteCitation: "Haw. Rev. Stat. § 432E-6",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Hawaii Insurance Division",
    departmentPhone: "(808) 586-2790",
    departmentUrl: "https://cca.hawaii.gov/ins/",
    keyProvisions: [
      "Mandatory external review for health plan denials",
      "Written notification of denial with appeal rights",
      "Standard and expedited review timelines",
      "Consumer protection under unfair practices act",
    ],
    penaltyForNonCompliance: "Administrative penalties and license sanctions",
  },
  {
    code: "ID",
    name: "Idaho",
    country: "US",
    statute: "Idaho Insurance Code",
    statuteCitation: "Idaho Code § 41-1329",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Idaho Department of Insurance",
    departmentPhone: "(208) 334-4250",
    departmentUrl: "https://doi.idaho.gov",
    keyProvisions: [
      "Unfair settlement practices prohibited",
      "Written denial required within reasonable timeframe",
      "External review available for covered persons",
      "Consumer complaint process through DOI",
    ],
    penaltyForNonCompliance: "Fines and potential license revocation",
  },
  {
    code: "IL",
    name: "Illinois",
    country: "US",
    statute: "Illinois Insurance Code",
    statuteCitation: "215 ILCS 5/154.6",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Illinois Department of Insurance",
    departmentPhone: "(866) 445-5364",
    departmentUrl: "https://insurance.illinois.gov",
    keyProvisions: [
      "External review for adverse medical necessity determinations",
      "Written denial with clinical rationale required",
      "Expedited review for urgent conditions",
      "Coverage under HMO Act and Managed Care Reform Act",
    ],
    penaltyForNonCompliance: "Fines up to $50,000 for pattern of violations",
  },
  {
    code: "IN",
    name: "Indiana",
    country: "US",
    statute: "Indiana Insurance Code",
    statuteCitation: "Ind. Code § 27-8-28",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Indiana Department of Insurance",
    departmentPhone: "(317) 232-2385",
    departmentUrl: "https://www.in.gov/idoi/",
    keyProvisions: [
      "External review act for health coverage denials",
      "Written denial with specific reasons required",
      "Binding external review decisions",
      "Consumer assistance available through IDOI",
    ],
    penaltyForNonCompliance: "Administrative penalties and corrective orders",
  },
  {
    code: "IA",
    name: "Iowa",
    country: "US",
    statute: "Iowa Insurance Code",
    statuteCitation: "Iowa Code § 514J",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Iowa Insurance Division",
    departmentPhone: "(515) 281-5705",
    departmentUrl: "https://iid.iowa.gov",
    keyProvisions: [
      "External review for adverse benefit determinations",
      "Written denial with appeal procedures required",
      "Standard and expedited review processes",
      "Consumer protection under unfair practices chapter",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "KS",
    name: "Kansas",
    country: "US",
    statute: "Kansas Insurance Code",
    statuteCitation: "Kan. Stat. Ann. § 40-2,125a",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Kansas Insurance Department",
    departmentPhone: "(785) 296-3071",
    departmentUrl: "https://insurance.kansas.gov",
    keyProvisions: [
      "Independent external review for health plan denials",
      "Written notification of denial and appeal rights",
      "Binding external review decisions",
      "Unfair claims settlement practices act",
    ],
    penaltyForNonCompliance: "Fines and potential license action",
  },
  {
    code: "KY",
    name: "Kentucky",
    country: "US",
    statute: "Kentucky Insurance Code",
    statuteCitation: "Ky. Rev. Stat. § 304.17A-600",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Kentucky Department of Insurance",
    departmentPhone: "(800) 595-6053",
    departmentUrl: "https://insurance.ky.gov",
    keyProvisions: [
      "External review for adverse determinations",
      "Written denial with clinical basis required",
      "Expedited review for urgent health conditions",
      "Unfair claims practices protections",
    ],
    penaltyForNonCompliance: "Administrative fines and enforcement actions",
  },
  {
    code: "LA",
    name: "Louisiana",
    country: "US",
    statute: "Louisiana Insurance Code",
    statuteCitation: "La. Rev. Stat. § 22:1892",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Louisiana Department of Insurance",
    departmentPhone: "(225) 342-5900",
    departmentUrl: "https://www.ldi.la.gov",
    keyProvisions: [
      "Prompt payment: 30-day requirement for claims",
      "Penalties for arbitrary denial: 50% of claim + attorney fees",
      "Written denial with specific reasons required",
      "External review rights for health plan members",
    ],
    penaltyForNonCompliance:
      "Up to 50% penalty on claim plus attorney fees under § 22:1892",
  },
  {
    code: "ME",
    name: "Maine",
    country: "US",
    statute: "Maine Insurance Code",
    statuteCitation: "Me. Rev. Stat. Ann. tit. 24-A, § 4312",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Maine Bureau of Insurance",
    departmentPhone: "(800) 300-5000",
    departmentUrl: "https://www.maine.gov/pfr/insurance",
    keyProvisions: [
      "External review for carrier adverse decisions",
      "Written denial with appeal instructions required",
      "Independent review organization process",
      "Consumer assistance program",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement orders",
  },
  {
    code: "MD",
    name: "Maryland",
    country: "US",
    statute: "Maryland Insurance Article",
    statuteCitation: "Md. Code Ann., Ins. § 15-10A-02",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Maryland Insurance Administration",
    departmentPhone: "(410) 468-2000",
    departmentUrl: "https://insurance.maryland.gov",
    keyProvisions: [
      "Mandatory internal grievance and external review",
      "Written denial with clinical rationale required",
      "Binding external review through IRO",
      "Complaint process through MIA",
    ],
    penaltyForNonCompliance: "Fines up to $25,000 per violation",
  },
  {
    code: "MA",
    name: "Massachusetts",
    country: "US",
    statute: "Massachusetts Insurance Code",
    statuteCitation: "Mass. Gen. Laws ch. 176O, § 14",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Massachusetts Division of Insurance",
    departmentPhone: "(877) 563-4467",
    departmentUrl: "https://www.mass.gov/orgs/division-of-insurance",
    keyProvisions: [
      "External review rights under managed care law",
      "Written denial required with appeal rights",
      "Office of Patient Protection handles external reviews",
      "Unfair claims settlement practices: ch. 176D, § 3(9)",
    ],
    penaltyForNonCompliance:
      "Administrative penalties, license action, civil remedies",
  },
  {
    code: "MI",
    name: "Michigan",
    country: "US",
    statute: "Michigan Insurance Code",
    statuteCitation: "Mich. Comp. Laws § 500.2006",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance:
      "Michigan Department of Insurance and Financial Services",
    departmentPhone: "(877) 999-6442",
    departmentUrl: "https://www.michigan.gov/difs",
    keyProvisions: [
      "Unfair trade practices and claims settlement",
      "Written denial with reasons and appeal rights",
      "External review process available",
      "DIFS complaint resolution",
    ],
    penaltyForNonCompliance: "Fines up to $50,000 for violations",
  },
  {
    code: "MN",
    name: "Minnesota",
    country: "US",
    statute: "Minnesota Insurance Code",
    statuteCitation: "Minn. Stat. § 62Q.73",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Minnesota Department of Commerce",
    departmentPhone: "(651) 539-1600",
    departmentUrl: "https://mn.gov/commerce/",
    keyProvisions: [
      "External review for health plan adverse determinations",
      "Written denial with clinical basis required",
      "Standard and expedited review timelines",
      "Consumer protections under unfair practices act",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "MS",
    name: "Mississippi",
    country: "US",
    statute: "Mississippi Insurance Code",
    statuteCitation: "Miss. Code Ann. § 83-9-5",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Mississippi Insurance Department",
    departmentPhone: "(601) 359-3569",
    departmentUrl: "https://www.mid.ms.gov",
    keyProvisions: [
      "Unfair claims settlement practices prohibited",
      "Written denial with reasons required",
      "External review process available",
      "Consumer complaint resolution",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement actions",
  },
  {
    code: "MO",
    name: "Missouri",
    country: "US",
    statute: "Missouri Insurance Code",
    statuteCitation: "Mo. Rev. Stat. § 376.1363",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Missouri Department of Commerce and Insurance",
    departmentPhone: "(573) 751-4126",
    departmentUrl: "https://insurance.mo.gov",
    keyProvisions: [
      "External review for health carrier adverse decisions",
      "Written denial required with specific reasons",
      "IRO review binding on health carrier",
      "Consumer assistance and complaint process",
    ],
    penaltyForNonCompliance: "Fines and potential license action",
  },
  {
    code: "MT",
    name: "Montana",
    country: "US",
    statute: "Montana Insurance Code",
    statuteCitation: "Mont. Code Ann. § 33-18-201",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Montana Commissioner of Securities and Insurance",
    departmentPhone: "(406) 444-2040",
    departmentUrl: "https://csimt.gov",
    keyProvisions: [
      "Unfair trade practices in insurance",
      "Written denial with reasons required",
      "External review for health plan denials",
      "Independent adjuster requirement for complex claims",
    ],
    penaltyForNonCompliance: "Fines up to $5,000 per violation",
  },
  {
    code: "NE",
    name: "Nebraska",
    country: "US",
    statute: "Nebraska Insurance Code",
    statuteCitation: "Neb. Rev. Stat. § 44-1540",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Nebraska Department of Insurance",
    departmentPhone: "(402) 471-2201",
    departmentUrl: "https://doi.nebraska.gov",
    keyProvisions: [
      "Unfair claims settlement practices act",
      "Written denial with appeal procedures",
      "External review available for adverse determinations",
      "Consumer hotline and assistance",
    ],
    penaltyForNonCompliance: "Administrative fines and corrective actions",
  },
  {
    code: "NV",
    name: "Nevada",
    country: "US",
    statute: "Nevada Insurance Code",
    statuteCitation: "Nev. Rev. Stat. § 686A.310",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Nevada Division of Insurance",
    departmentPhone: "(775) 687-0700",
    departmentUrl: "https://doi.nv.gov",
    keyProvisions: [
      "Unfair practices in settling claims",
      "Written denial with specific reasons required",
      "External review for health insurance denials",
      "Bad faith provisions under NRS 686A.310",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "NH",
    name: "New Hampshire",
    country: "US",
    statute: "New Hampshire Insurance Code",
    statuteCitation: "N.H. Rev. Stat. Ann. § 420-J:5",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "New Hampshire Insurance Department",
    departmentPhone: "(603) 271-2261",
    departmentUrl: "https://www.nh.gov/insurance/",
    keyProvisions: [
      "External review for managed care adverse decisions",
      "Written denial with clinical basis required",
      "Binding external review through IRO",
      "Consumer assistance program",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },
  {
    code: "NJ",
    name: "New Jersey",
    country: "US",
    statute: "New Jersey Insurance Code",
    statuteCitation: "N.J. Stat. Ann. § 26:2S-11",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "New Jersey Department of Banking and Insurance",
    departmentPhone: "(609) 292-7272",
    departmentUrl: "https://www.state.nj.us/dobi/",
    keyProvisions: [
      "Health plan grievance and appeal rights",
      "Independent utilization review for denials",
      "Written denial with appeal procedures",
      "DOBI complaint resolution process",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "NM",
    name: "New Mexico",
    country: "US",
    statute: "New Mexico Insurance Code",
    statuteCitation: "N.M. Stat. Ann. § 59A-16-20",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "New Mexico Office of Superintendent of Insurance",
    departmentPhone: "(855) 427-5674",
    departmentUrl: "https://www.osi.state.nm.us",
    keyProvisions: [
      "Unfair claims practices act",
      "Written denial with reasons required",
      "External review available",
      "Consumer complaint process through OSI",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },
  {
    code: "NY",
    name: "New York",
    country: "US",
    statute: "New York Insurance Law",
    statuteCitation: "N.Y. Ins. Law § 4914",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "New York Department of Financial Services",
    departmentPhone: "(800) 342-3736",
    departmentUrl: "https://www.dfs.ny.gov",
    keyProvisions: [
      "Strong external review rights under Insurance Law § 4914",
      "Written denial with clinical rationale mandatory",
      "DFS external appeal process - binding on insurer",
      "Utilization review agent requirements",
      "Prompt pay law: 30 days for clean claims",
      "Unfair claims practices: N.Y. Ins. Law § 2601",
    ],
    penaltyForNonCompliance:
      "Fines up to $5,000 per violation, license suspension",
  },
  {
    code: "NC",
    name: "North Carolina",
    country: "US",
    statute: "North Carolina Insurance Code",
    statuteCitation: "N.C. Gen. Stat. § 58-50-61",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "North Carolina Department of Insurance",
    departmentPhone: "(855) 408-1212",
    departmentUrl: "https://www.ncdoi.gov",
    keyProvisions: [
      "External review for noncertification decisions",
      "Written denial with specific reasons required",
      "Second-level grievance review process",
      "Consumer assistance through NCDOI",
    ],
    penaltyForNonCompliance: "Fines up to $1,000 per violation",
  },
  {
    code: "ND",
    name: "North Dakota",
    country: "US",
    statute: "North Dakota Insurance Code",
    statuteCitation: "N.D. Cent. Code § 26.1-36.6",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "North Dakota Insurance Department",
    departmentPhone: "(701) 328-2440",
    departmentUrl: "https://www.insurance.nd.gov",
    keyProvisions: [
      "External review for adverse health insurance determinations",
      "Written denial with appeal rights required",
      "Binding IRO review",
      "Consumer complaint resolution",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },
  {
    code: "OH",
    name: "Ohio",
    country: "US",
    statute: "Ohio Insurance Code",
    statuteCitation: "Ohio Rev. Code § 3922.01 et seq.",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Ohio Department of Insurance",
    departmentPhone: "(800) 686-1526",
    departmentUrl: "https://insurance.ohio.gov",
    keyProvisions: [
      "Health Plan External Review Act",
      "Written denial required with clinical rationale",
      "Independent external review binding on insurer",
      "Consumer complaint hotline",
      "Unfair claims settlement practices: ORC § 3901.21",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "OK",
    name: "Oklahoma",
    country: "US",
    statute: "Oklahoma Insurance Code",
    statuteCitation: "Okla. Stat. tit. 36, § 1250.5",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Oklahoma Insurance Department",
    departmentPhone: "(405) 521-2828",
    departmentUrl: "https://www.oid.ok.gov",
    keyProvisions: [
      "Unfair claims settlement practices act",
      "Written denial required with reasons",
      "External review for health plan denials",
      "Consumer assistance program",
    ],
    penaltyForNonCompliance: "Fines and enforcement actions",
  },
  {
    code: "OR",
    name: "Oregon",
    country: "US",
    statute: "Oregon Insurance Code",
    statuteCitation: "Or. Rev. Stat. § 743B.250",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Oregon Division of Financial Regulation",
    departmentPhone: "(503) 947-7980",
    departmentUrl: "https://dfr.oregon.gov",
    keyProvisions: [
      "External review for adverse benefit determinations",
      "Written denial with clinical reasons required",
      "Binding independent review",
      "Consumer advocacy and complaint process",
    ],
    penaltyForNonCompliance: "Administrative fines and corrective actions",
  },
  {
    code: "PA",
    name: "Pennsylvania",
    country: "US",
    statute: "Pennsylvania Insurance Code",
    statuteCitation: "40 Pa. Stat. § 991.2166",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Pennsylvania Insurance Department",
    departmentPhone: "(877) 881-6388",
    departmentUrl: "https://www.insurance.pa.gov",
    keyProvisions: [
      "External review under Act 68 (HMO Act)",
      "Written denial with specific clinical basis required",
      "Utilization review entity requirements",
      "Consumer complaint and grievance process",
      "Bad faith provisions: 42 Pa. Cons. Stat. § 8371",
    ],
    penaltyForNonCompliance:
      "Bad faith damages including punitive damages, attorney fees",
  },
  {
    code: "RI",
    name: "Rhode Island",
    country: "US",
    statute: "Rhode Island Insurance Code",
    statuteCitation: "R.I. Gen. Laws § 27-18.7",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Rhode Island Department of Business Regulation",
    departmentPhone: "(401) 462-9520",
    departmentUrl: "https://dbr.ri.gov",
    keyProvisions: [
      "External review for adverse benefit determinations",
      "Written denial with appeal procedures",
      "Independent reviewer process",
      "Consumer protection and assistance",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },
  {
    code: "SC",
    name: "South Carolina",
    country: "US",
    statute: "South Carolina Insurance Code",
    statuteCitation: "S.C. Code Ann. § 38-71-1950",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "South Carolina Department of Insurance",
    departmentPhone: "(803) 737-6160",
    departmentUrl: "https://www.doi.sc.gov",
    keyProvisions: [
      "External review for health insurance denials",
      "Written denial with clinical reasons required",
      "Binding independent review",
      "Consumer complaint process",
    ],
    penaltyForNonCompliance: "Fines and potential license action",
  },
  {
    code: "SD",
    name: "South Dakota",
    country: "US",
    statute: "South Dakota Insurance Code",
    statuteCitation: "S.D. Codified Laws § 58-17H",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "South Dakota Division of Insurance",
    departmentPhone: "(605) 773-3563",
    departmentUrl: "https://dlr.sd.gov/insurance/",
    keyProvisions: [
      "External review act for managed care denials",
      "Written denial with reasons and appeal rights",
      "Independent review organization process",
      "Consumer complaint resolution",
    ],
    penaltyForNonCompliance: "Administrative penalties",
  },
  {
    code: "TN",
    name: "Tennessee",
    country: "US",
    statute: "Tennessee Insurance Code",
    statuteCitation: "Tenn. Code Ann. § 56-32-226",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Tennessee Department of Commerce and Insurance",
    departmentPhone: "(615) 741-2241",
    departmentUrl: "https://www.tn.gov/commerce/insurance.html",
    keyProvisions: [
      "External review for HMO/managed care denials",
      "Written denial required with appeal rights",
      "Binding external review through certified IRO",
      "Consumer complaint and assistance",
    ],
    penaltyForNonCompliance: "Fines and enforcement actions",
  },
  {
    code: "TX",
    name: "Texas",
    country: "US",
    statute: "Texas Insurance Code",
    statuteCitation: "Tex. Ins. Code § 4201.359",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Texas Department of Insurance",
    departmentPhone: "(800) 252-3439",
    departmentUrl: "https://www.tdi.texas.gov",
    keyProvisions: [
      "Independent Review Organization (IRO) process",
      "Written denial with clinical rationale required",
      "Binding IRO review for medical necessity",
      "Unfair settlement practices: Tex. Ins. Code § 541",
      "Prompt payment: 5 days for electronic, 15 for paper claims",
      "Consumer Bill of Rights",
    ],
    penaltyForNonCompliance:
      "Penalties up to $25,000 per violation, treble damages for Prompt Pay violations",
  },
  {
    code: "UT",
    name: "Utah",
    country: "US",
    statute: "Utah Insurance Code",
    statuteCitation: "Utah Code Ann. § 31A-26-301.6",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Utah Insurance Department",
    departmentPhone: "(801) 538-3800",
    departmentUrl: "https://insurance.utah.gov",
    keyProvisions: [
      "External review for adverse benefit determinations",
      "Written denial required with appeal instructions",
      "Independent review organization process",
      "Consumer assistance through UID",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },
  {
    code: "VT",
    name: "Vermont",
    country: "US",
    statute: "Vermont Insurance Code",
    statuteCitation: "Vt. Stat. Ann. tit. 8, § 4089f",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Vermont Department of Financial Regulation",
    departmentPhone: "(802) 828-3301",
    departmentUrl: "https://dfr.vermont.gov",
    keyProvisions: [
      "External review for adverse health insurance decisions",
      "Written denial with reasons and appeal information",
      "Binding independent review",
      "Consumer assistance and complaint process",
    ],
    penaltyForNonCompliance: "Administrative penalties",
  },
  {
    code: "VA",
    name: "Virginia",
    country: "US",
    statute: "Virginia Insurance Code",
    statuteCitation: "Va. Code Ann. § 38.2-5900",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Virginia Bureau of Insurance",
    departmentPhone: "(804) 371-9741",
    departmentUrl: "https://www.scc.virginia.gov/boi/",
    keyProvisions: [
      "External review act for health plan denials",
      "Written denial with clinical rationale required",
      "Independent review organization process",
      "Consumer complaint resolution through BOI",
    ],
    penaltyForNonCompliance: "Fines and enforcement actions",
  },
  {
    code: "WA",
    name: "Washington",
    country: "US",
    statute: "Washington Insurance Code",
    statuteCitation: "Wash. Rev. Code § 48.43.535",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Washington Office of Insurance Commissioner",
    departmentPhone: "(800) 562-6900",
    departmentUrl: "https://www.insurance.wa.gov",
    keyProvisions: [
      "External review through IRO for adverse decisions",
      "Written denial with clinical basis required",
      "Balance billing protections",
      "Strong consumer protections under RCW 48.43",
      "Insurance commissioner complaint process",
    ],
    penaltyForNonCompliance:
      "Fines up to $10,000 per violation, license action",
  },
  {
    code: "WV",
    name: "West Virginia",
    country: "US",
    statute: "West Virginia Insurance Code",
    statuteCitation: "W. Va. Code § 33-25D",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "West Virginia Offices of Insurance Commissioner",
    departmentPhone: "(304) 558-3386",
    departmentUrl: "https://www.wvinsurance.gov",
    keyProvisions: [
      "External review for health plan adverse determinations",
      "Written denial required with appeal procedures",
      "Independent review organization review",
      "Consumer assistance program",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },
  {
    code: "WI",
    name: "Wisconsin",
    country: "US",
    statute: "Wisconsin Insurance Code",
    statuteCitation: "Wis. Stat. § 632.835",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Wisconsin Office of Commissioner of Insurance",
    departmentPhone: "(608) 266-3585",
    departmentUrl: "https://oci.wi.gov",
    keyProvisions: [
      "Independent review for adverse determinations",
      "Written denial with clinical reasons required",
      "Binding external review",
      "Consumer complaint and assistance process",
    ],
    penaltyForNonCompliance: "Fines up to $10,000 per violation",
  },
  {
    code: "WY",
    name: "Wyoming",
    country: "US",
    statute: "Wyoming Insurance Code",
    statuteCitation: "Wyo. Stat. § 26-40-201",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Wyoming Insurance Department",
    departmentPhone: "(307) 777-7401",
    departmentUrl: "https://doi.wyo.gov",
    keyProvisions: [
      "External review for health plan denials",
      "Written denial with reasons required",
      "Independent review organization process",
      "Consumer complaint resolution",
    ],
    penaltyForNonCompliance: "Administrative penalties",
  },
  {
    code: "DC",
    name: "District of Columbia",
    country: "US",
    statute: "DC Insurance Code",
    statuteCitation: "D.C. Code § 31-3861",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "DC Department of Insurance, Securities and Banking",
    departmentPhone: "(202) 727-8000",
    departmentUrl: "https://disb.dc.gov",
    keyProvisions: [
      "External review for adverse health benefit determinations",
      "Written denial with appeal rights required",
      "Independent review process",
      "Consumer complaint assistance",
    ],
    penaltyForNonCompliance: "Administrative penalties and enforcement",
  },

  // ── UNITED KINGDOM ──────────────────────────────────────────
  {
    code: "UK",
    name: "United Kingdom",
    country: "UK",
    statute:
      "Financial Conduct Authority Insurance Conduct of Business Sourcebook (ICOBS)",
    statuteCitation: "ICOBS 8.1 - Claims Handling",
    filingDeadlineDays: 180,
    externalReviewAvailable: true,
    departmentOfInsurance: "Financial Ombudsman Service (FOS)",
    departmentPhone: "+44 800 023 4567",
    departmentUrl: "https://www.financial-ombudsman.org.uk",
    keyProvisions: [
      "FCA requires fair and prompt claims handling under ICOBS 8.1",
      "Right to complain to Financial Ombudsman Service",
      "Insurer must provide final response within 8 weeks",
      "FOS can award up to £415,000 in compensation",
      "Consumer Insurance (Disclosure and Representations) Act 2012",
      "Insurance Act 2015 - duty of fair presentation",
    ],
    penaltyForNonCompliance:
      "FCA regulatory action, FOS compensation awards up to £415,000",
  },

  // ── CANADA ──────────────────────────────────────────────────
  {
    code: "CA-ON",
    name: "Canada (Ontario)",
    country: "CA",
    statute: "Ontario Insurance Act",
    statuteCitation: "R.S.O. 1990, c. I.8, s. 148",
    filingDeadlineDays: 365,
    externalReviewAvailable: true,
    departmentOfInsurance:
      "Financial Services Regulatory Authority of Ontario (FSRA)",
    departmentPhone: "+1 (416) 250-7250",
    departmentUrl: "https://www.fsrao.ca",
    keyProvisions: [
      "Right to dispute through FSRA arbitration",
      "Statutory accident benefits dispute resolution",
      "Written denial with reasons required under Insurance Act",
      "Ontario Health Insurance Plan (OHIP) appeal rights",
      "Unfair or deceptive acts prohibited",
    ],
    penaltyForNonCompliance:
      "FSRA enforcement actions, arbitration awards, penalties up to $100,000",
  },
  {
    code: "CA-BC",
    name: "Canada (British Columbia)",
    country: "CA",
    statute: "BC Financial Institutions Act",
    statuteCitation: "RSBC 1996, c. 141",
    filingDeadlineDays: 365,
    externalReviewAvailable: true,
    departmentOfInsurance: "BC Financial Services Authority (BCFSA)",
    departmentPhone: "+1 (604) 953-5300",
    departmentUrl: "https://www.bcfsa.ca",
    keyProvisions: [
      "Right to independent dispute resolution",
      "Written denial with appeal instructions required",
      "Provincial health services appeal mechanism",
      "Consumer complaint process through BCFSA",
    ],
    penaltyForNonCompliance: "Regulatory enforcement and penalties",
  },

  // ── AUSTRALIA ────────────────────────────────────────────────
  {
    code: "AU",
    name: "Australia",
    country: "AU",
    statute: "Insurance Contracts Act 1984 (Cth)",
    statuteCitation: "Insurance Contracts Act 1984, Part V",
    filingDeadlineDays: 365,
    externalReviewAvailable: true,
    departmentOfInsurance: "Australian Financial Complaints Authority (AFCA)",
    departmentPhone: "+61 1800 931 678",
    departmentUrl: "https://www.afca.org.au",
    keyProvisions: [
      "Duty of utmost good faith under Insurance Contracts Act s.13",
      "Right to internal dispute resolution (IDR)",
      "AFCA external dispute resolution (EDR) - free service",
      "Insurer must respond to complaints within 30 days",
      "AFCA can award compensation up to $1,085,000",
      "General Insurance Code of Practice 2020",
    ],
    penaltyForNonCompliance:
      "APRA/ASIC enforcement, AFCA compensation awards up to $1,085,000",
  },
];

// Helper functions
export function getStateLaw(code: string): StateLaw | undefined {
  return stateLaws.find((s) => s.code.toLowerCase() === code.toLowerCase());
}

export function getStateLawsByCountry(
  country: "US" | "UK" | "CA" | "AU",
): StateLaw[] {
  return stateLaws.filter((s) => s.country === country);
}

export function getAllUSStates(): StateLaw[] {
  return stateLaws.filter((s) => s.country === "US");
}

export function getAllStateCodes(): string[] {
  return stateLaws.map((s) => s.code);
}
